Watching for file changes with StatReloader
"GET /admin/challenges/quizquestion/1/change/ HTTP/1.1" 200 23850
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
Internal Server Error: /admin/challenges/quizquestion/1/change/
Traceback (most recent call last):
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\psycopg\cursor.py", line 732, in execute
    raise ex.with_traceback(None)
psycopg.errors.StringDataRightTruncation: value too long for type character varying(50)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\contrib\admin\options.py", line 1948, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\contrib\admin\options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\contrib\admin\options.py", line 1855, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\contrib\admin\options.py", line 1259, in save_model
    obj.save()
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\challenges\models.py", line 70, in save
    super().save(*args, **kwargs)
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\db\models\base.py", line 1036, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\db\models\base.py", line 1101, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\db\models\query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1990, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bilim\Documents\backend\django\pro\devsplug\env\Lib\site-packages\psycopg\cursor.py", line 732, in execute
    raise ex.with_traceback(None)
django.db.utils.DataError: value too long for type character varying(50)
"POST /admin/challenges/quizquestion/1/change/ HTTP/1.1" 500 145
C:\Users\bilim\Documents\backend\django\pro\devsplug\challenges\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\bilim\Documents\backend\django\pro\devsplug\challenges\models.py changed, reloading.
Watching for file changes with StatReloader
"POST /admin/challenges/quizquestion/1/change/ HTTP/1.1" 302 0
"GET /admin/challenges/quizquestion/ HTTP/1.1" 200 21536
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
C:\Users\bilim\Documents\backend\django\pro\devsplug\challenges\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\bilim\Documents\backend\django\pro\devsplug\challenges\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\bilim\Documents\backend\django\pro\devsplug\challenges\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\bilim\Documents\backend\django\pro\devsplug\challenges\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\bilim\Documents\backend\django\pro\devsplug\challenges\models.py changed, reloading.
Watching for file changes with StatReloader
